#!/bin/sh
set -o errexit
set -o nounset

main() {
    echo "removing old deploy zip & clearing build dir"
    rm -rf build
    rm -f deploy.zip
    echo "compiling source files"

    release_name="$(git rev-parse head)"

    ./node_modules/.bin/esbuild \
        src/index.ts \
        --platform=node \
        --define:process.env.TTD_SENTRY_RELEASE="'${release_name}'" \
        --bundle \
        --minify \
        --sourcemap \
        --target=node12 \
        --outfile=build/index.js

    echo "zipping source files"
    zip --recurse-paths --junk-paths --quiet deploy.zip build/index.js
    du -h deploy.zip
    echo "done"
}

main "$@"
