#!/bin/sh
set -o errexit
set -o nounset

main() {
    echo "removing old deploy zip & clearing build dir"
    rm -rf build
    rm -f deploy.zip
    echo "compiling source files"
    ./node_modules/.bin/esbuild index.ts --platform=node --bundle --minify --sourcemap --target=node12 --outfile=build/index.js
    echo "zipping source files"
    zip --recurse-paths --junk-paths --quiet deploy.zip build/index.js
    du -h deploy.zip
    echo "done"
}

main "$@"
